### ISSUE TITLE
Error while project setup

### ISSUE THREAD

**Issue by dineshdb** [locus-ioe/lis#1]
I get following __error__ when I run _make install_. It's actually a error due to a missing file  **web.xml**.

`
composer install
Cannot create cache directory /home/dineshdb/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/dineshdb/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Class 'DOMDocument' not found in /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(284): Symfony\Component\Config\Util\XmlUtils::loadFile('/home/dineshdb/...', Array)
#1 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/home/dineshdb/...')
#2 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(58): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/src/S in /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

                                                                               
  [RuntimeException]                                                           
  An error occurred when executing the "'cache:clear --no-warmup'" command:    
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowable  
  Error: Fatal error: Class 'DOMDocument' not found in /home/dineshdb/Project  
  s/github.com/dineshdb/lis/vendor/symfony/symfony/src/Symfony/Component/Conf  
  ig/Util/XmlUtils.php:52                                                      
  Stack trace:                                                                 
  #0 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/s  
  rc/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(284): Sym  
  fony\Component\Config\Util\XmlUtils::loadFile('/home/dineshdb/...', Array)   
  #1 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/s  
  rc/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symf  
  ony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/ho  
  me/dineshdb/...')                                                            
  #2 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/s  
  rc/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.ph  
  p(58): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('we  
  b.xml')                                                                      
  #3 /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symfony/s  
  rc/S in /home/dineshdb/Projects/github.com/dineshdb/lis/vendor/symfony/symf  
  ony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52                
  .                                                                            
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

makefile:9: recipe for target 'install' failed
make: *** [install] Error 
`

**Comment by RaazPuspa** [comment]
I had tried a fresh clone and install on my system (Ubuntu 16.04) and it worked without any issues. With this, I think there might be some dependency or permission issues on your system. Let you check those things and retry once again. If it appears again we need to think differently.

**Comment by dineshdb** [comment]
This seems to be a dependency issue. I would like to contribute to this project but I'm having trouble setting up. Please send me detailed info to set up this project in Ubuntu GNOME 16.10

**Comment by RaazPuspa** [comment]
The steps mentioned in readme file works properly for Ubuntu GNOME too (tested and verified on 16.04 LTS).

**Comment by dineshdb** [comment]
That didn't help me!

**Comment by dineshdb** [comment]
I don't think I'm getting help on this. Thank you!

**Comment by RaazPuspa** [comment]
Let you try stackoverflow and those google things. They will be helpful as I am unable to figure out your problem. Sorry.
